import { useState } from 'react';
import { Download,Plus,Settings,Eye,RotateCcw,ShieldOff } from 'lucide-react';
import { api } from './api';
import { type State,type Action,type User,type Job,KIND,active,pending,duration,nodeStatus } from './types';
import { Stat,Badge,Modal,Empty } from './ui';
import { JobDetail } from './Jobs';
export function Admin({state,action}:{state:State;action:Action}){
 const [tab,setTab]=useState('jobs');const [edit,setEdit]=useState<User|null>(null);const [create,setCreate]=useState(false);const [view,setView]=useState<string|null>(null);const [reset,setReset]=useState(false);const [chosen,setChosen]=useState<string[]>([]);const [confirm,setConfirm]=useState<{title:string;text:string;run:()=>Promise<void>}|null>(null);
 const jobs=state.jobs;const complete=jobs.filter(j=>j.status==='completed');const ended=jobs.filter(j=>['completed','failed'].includes(j.status));const waits=jobs.filter(j=>j.attempts.length).map(j=>j.attempts[0].started_at-j.created_at);const demos=jobs.filter(j=>j.is_demo);const batchIds=[...new Set(demos.map(j=>j.batch_id))];const selected=jobs.find(j=>j.id===view);
 function cancel(j:Job){setConfirm({title:'取消工作',text:`確認取消「${j.filename}」？取消後不會自動重試。`,run:async()=>{await api('/jobs/'+j.id+'/cancel','POST')}})}
 return <><div className="page-heading"><div><span className="eyebrow">平台營運</span><h1>平台管理</h1><p>查看派工與接力紀錄，管理校內帳號及設備。統計範圍為最近 500 件未封存工作。</p></div><a className="button secondary" href="/api/admin/report"><Download size={17}/>匯出工作報表</a></div>
 <div className="stats-grid"><Stat label="在線設備" value={state.nodes.filter(n=>n.online&&!n.revoked).length} detail="20 秒內曾回報" accent/><Stat label="成功工作" value={complete.length} detail="每個檔案只計算一次"/><Stat label="完成率" value={ended.length?(complete.length/ended.length*100).toFixed(1)+'%':'—'} detail="完成 /（完成＋失敗），不含取消"/><Stat label="平均排隊時間" value={waits.length?duration(waits.reduce((a,b)=>a+b,0)/waits.length):'—'} detail="提交至第一次派工"/></div>
 <div className="toolbar"><div className="segmented">{[['jobs','全部工作'],['users','帳號與額度'],['nodes','設備與貢獻'],['demo','示範資料']].map(([id,title])=><button key={id} className={id===tab?'chosen':''} onClick={()=>setTab(id)}>{title}</button>)}</div>{tab==='users'&&<button className="primary" onClick={()=>setCreate(true)}><Plus size={17}/>新增帳號</button>}</div>
 {tab==='jobs'&&<section className="panel table-wrap">{!jobs.length?<Empty title="還沒有工作紀錄" description="學生提交任務後，這裡會呈現每個檔案的處理狀態。"/>:<table><thead><tr><th>檔案 / 提交者</th><th>服務</th><th>狀態</th><th>設備 / 嘗試</th><th>操作</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><strong>{j.filename}</strong><small>{j.owner_name} · {j.batch_name}</small>{j.error&&<small className="error-text">{j.error}</small>}</td><td>{KIND[j.kind]}</td><td><Badge status={j.status}/></td><td>{j.attempts.at(-1)?.node_name||'等待派工'}<small>{j.attempt_count} 次執行</small></td><td><button className="icon-button" aria-label={`查看 ${j.filename}`} onClick={()=>setView(j.id)}><Eye size={18}/></button>{(active(j.status)||pending(j.status))&&<button className="text-button" onClick={()=>cancel(j)}>取消</button>}</td></tr>)}</tbody></table>}</section>}
 {tab==='users'&&<section className="panel table-wrap"><table><thead><tr><th>帳號</th><th>角色 / 狀態</th><th>同時工作上限</th><th>24 小時提交額度</th><th>操作</th></tr></thead><tbody>{state.users.map(u=><tr key={u.id}><td><strong>{u.display_name}</strong><small>{u.username}</small></td><td>{u.role==='admin'?'管理者':'使用者'} · {u.enabled?'啟用':'停用'}</td><td>{u.max_running} 件</td><td>{u.daily_limit} 件</td><td><button className="secondary compact" onClick={()=>setEdit(u)}><Settings size={16}/>管理</button></td></tr>)}</tbody></table></section>}
 {tab==='nodes'&&<section className="panel table-wrap"><table><thead><tr><th>設備 / GPU</th><th>狀態</th><th>完成工作</th><th>GPU 運算時間</th><th>操作</th></tr></thead><tbody>{state.nodes.map(n=><tr key={n.id}><td><strong>{n.name}</strong><small>{n.gpu_name} · {n.owner_name}</small></td><td>{nodeStatus(n)}</td><td>{n.completed_count}</td><td>{duration(n.compute_seconds)}</td><td>{!n.revoked?<button className="text-button error-text" onClick={()=>setConfirm({title:'撤銷設備',text:`撤銷「${n.name}」的憑證，當前工作會重新排隊。重新加入需要新的配對碼。`,run:async()=>{await api('/nodes/'+n.id,'PATCH',{revoked:true})}})}><ShieldOff size={16}/>撤銷</button>:<button className="text-button" onClick={()=>setConfirm({title:'允許重新配對',text:'保留歷史紀錄，釋出這張 GPU 的設備識別，以便重新加入。',run:async()=>{await api('/admin/nodes/'+n.id,'DELETE')}})}>允許重新配對</button>}</td></tr>)}</tbody></table><p className="table-note">運算時間取自成功工作的容器 GPU 推論計時；硬體數據不支援時顯示未提供。</p></section>}
 {tab==='demo'&&<section className="panel panel-body"><h2>整理指定的示範批次</h2><p className="muted">只處理提交時勾選「示範資料」的批次。重置會取消未完成工作並封存；檔案與歷史保留，可還原查看。</p>{batchIds.length?batchIds.map(id=><label className="check-row" key={id}><input type="checkbox" checked={chosen.includes(id)} onChange={e=>setChosen(e.target.checked?[...chosen,id]:chosen.filter(x=>x!==id))}/><span>{demos.find(j=>j.batch_id===id)?.batch_name}<small>{demos.filter(j=>j.batch_id===id).length} 件工作</small></span></label>):<Empty title="沒有未封存的示範批次" description="建立任務時勾選示範資料，才能在這裡重置。"/>}<div className="modal-actions"><button className="secondary" onClick={()=>action(async()=>{await api('/admin/demo/restore','POST')},'示範批次已還原')}><RotateCcw size={17}/>還原示範批次</button><button className="danger" disabled={!chosen.length} onClick={()=>setReset(true)}>重置 {chosen.length} 個指定批次</button></div></section>}
 {selected&&<JobDetail job={selected} onClose={()=>setView(null)}/>}
 {confirm&&<Modal title={confirm.title} onClose={()=>setConfirm(null)}><p>{confirm.text}</p><div className="modal-actions"><button className="secondary" onClick={()=>setConfirm(null)}>返回</button><button className="danger" onClick={()=>action(async()=>{await confirm.run();setConfirm(null)},'操作已完成')}>確認{confirm.title}</button></div></Modal>}
 {reset&&<Modal title="重置指定示範批次" onClose={()=>setReset(false)}><p>將封存 {chosen.length} 個批次，尚未完成的工作會取消。輸入 RESET DEMO 確認。</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action(async()=>{await api('/admin/demo/reset','POST',{batch_ids:chosen,confirmation:f.get('confirmation')});setReset(false);setChosen([])},'指定示範批次已封存')}}><input name="confirmation" aria-label="重置確認文字" required pattern="RESET DEMO" autoComplete="off"/><div className="modal-actions"><button className="danger">封存指定批次</button></div></form></Modal>}
 {edit&&<Modal title="帳號與額度" onClose={()=>setEdit(null)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action(async()=>{await api('/admin/users/'+edit.id,'PATCH',{enabled:f.get('enabled')==='on',max_running:Number(f.get('max')),daily_limit:Number(f.get('daily'))});setEdit(null)},'帳號設定已儲存')}}><h3>{edit.display_name}</h3><label className="check-row"><input type="checkbox" name="enabled" defaultChecked={!!edit.enabled}/>啟用帳號</label><p className="muted">停用會登出帳號、取消其工作，並停止其設備分享。</p><label>同時工作上限<input name="max" type="number" min="1" max="8" required defaultValue={edit.max_running}/></label><label>24 小時提交額度<input name="daily" type="number" min="1" max="1000" required defaultValue={edit.daily_limit}/></label><div className="modal-actions"><button className="primary">儲存設定</button></div></form></Modal>}
 {create&&<Modal title="新增校內帳號" onClose={()=>setCreate(false)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action(async()=>{await api('/admin/users','POST',Object.fromEntries(f));setCreate(false)},'帳號已建立')}}><label>帳號<input name="username" required pattern="[A-Za-z0-9_.\-]{3,40}" autoComplete="off"/></label><label>顯示名稱<input name="display_name" required maxLength={60}/></label><label>初始密碼<input name="password" type="password" minLength={12} required autoComplete="new-password"/></label><label>角色<select name="role"><option value="member">使用者</option><option value="admin">管理者</option></select></label><div className="modal-actions"><button className="primary">建立帳號</button></div></form></Modal>}
 </>
}

