import { useEffect,useState } from 'react';
import { Search,Plus,Download,Eye,RotateCcw,XCircle,FileAudio,FileImage,CheckCircle2,ArrowRight,Clock3 } from 'lucide-react';
import { api } from './api';
import { type State,type Action,type Job,type Status,KIND,STATUS,date,duration,bytes,active,pending } from './types';
import { Badge,Empty,Modal } from './ui';
export function Jobs({state,action,onNew}:{state:State;action:Action;onNew:()=>void}){
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [selected,setSelected]=useState<string|null>(null);const [cancel,setCancel]=useState<Job|null>(null);
 const own=state.jobs.filter(j=>j.user_id===state.user.id);const jobs=own.filter(j=>(filter==='all'||j.status===filter)&&(j.filename+' '+j.batch_name).toLowerCase().includes(query.toLowerCase()));
 const batches=Array.from(new Set(jobs.map(j=>j.batch_id)));const selectedJob=state.jobs.find(j=>j.id===selected);
 return <><div className="page-heading"><div><span className="eyebrow">工作與成果</span><h1>我的工作</h1><p>追蹤每次接力，預覽並下載你的成果。顯示最近 500 件工作。</p></div><button className="primary" onClick={onNew}><Plus size={18}/>建立任務</button></div><div className="toolbar"><div className="search-field"><Search size={18}/><input aria-label="搜尋工作" placeholder="搜尋檔案或批次名稱" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="篩選工作狀態" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">所有狀態</option>{Object.entries(STATUS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><span className="result-count">{jobs.length} 件工作</span></div>
 {!jobs.length?<section className="panel"><Empty title={own.length?'沒有符合的工作':'目前還沒有工作'} description={own.length?'試著變更搜尋條件或狀態。':'上傳一份音訊或圖片，開始你的第一個任務。'}><button className="secondary" onClick={onNew}>建立任務 <ArrowRight size={16}/></button></Empty></section>:batches.map(batch=>{const shown=jobs.filter(j=>j.batch_id===batch);const all=own.filter(j=>j.batch_id===batch);const done=all.filter(j=>j.status==='completed').length;return <section className="panel batch-panel" key={batch}><div className="batch-heading"><div><h2>{shown[0].batch_name}{shown[0].is_demo===1&&<span className="demo-tag">示範</span>}</h2><p>{KIND[shown[0].kind]} · {date(shown[0].created_at)} · {done} / {all.length} 已完成</p></div>{done>0&&<a className="button secondary" href={'/api/batches/'+batch+'/download'}><Download size={16}/>下載成果</a>}</div><div className="batch-progress"><span style={{width:`${done/all.length*100}%`}}/></div><div className="job-list">{shown.map(j=><div className="job-row" key={j.id}><div className={'file-type '+j.kind}>{j.kind==='asr'?<FileAudio size={23}/>:<FileImage size={23}/>}</div><div className="job-name"><strong>{j.filename}</strong><small>{bytes(j.input_bytes)} · {j.attempts.at(-1)?.node_name||'等待可用設備'}{j.attempt_count>1&&` · 第 ${j.attempt_count} 次執行`}</small></div><div className="job-stage"><Badge status={j.status}/><small>{j.stage}</small></div><div className="job-actions"><button className="icon-button" title="查看詳情" aria-label={`查看 ${j.filename}`} onClick={()=>setSelected(j.id)}><Eye size={19}/></button>{active(j.status)||pending(j.status)?<button className="icon-button" title="取消工作" aria-label={`取消 ${j.filename}`} onClick={()=>setCancel(j)}><XCircle size={18}/></button>:<button className="icon-button" title="重新提交" aria-label={`重新提交 ${j.filename}`} onClick={()=>action(async()=>{await api('/jobs/'+j.id+'/retry','POST')},'已重新提交')}><RotateCcw size={18}/></button>}</div></div>)}</div></section>})}
 {selectedJob&&<JobDetail job={selectedJob} onClose={()=>setSelected(null)}/>} {cancel&&<Modal title="取消這個工作？" onClose={()=>setCancel(null)}><p>「{cancel.filename}」將停止執行，取消後不會自動重試。之後仍可重新提交。</p><div className="modal-actions"><button className="secondary" onClick={()=>setCancel(null)}>繼續執行</button><button className="danger" onClick={()=>action(async()=>{await api('/jobs/'+cancel.id+'/cancel','POST');setCancel(null)},'工作已取消')}>取消工作</button></div></Modal>}</>
}
export function JobDetail({job,onClose}:{job:Job;onClose:()=>void}){
 const [text,setText]=useState('');const [textError,setTextError]=useState('');const [split,setSplit]=useState(50);const transcript=job.artifacts.find(a=>a.name==='transcript.txt');const output=job.artifacts.find(a=>a.name==='upscaled.png');
 useEffect(()=>{if(!transcript)return;const c=new AbortController();fetch('/api/artifacts/'+transcript.id,{signal:c.signal}).then(r=>{if(!r.ok)throw Error('無法載入逐字稿');return r.text()}).then(setText).catch(e=>{if(e.name!=='AbortError')setTextError(e.message)});return()=>c.abort()},[transcript?.id]);
 return <Modal title="工作詳情與成果" onClose={onClose} wide><div className="detail-top"><div><h3>{job.filename}</h3><p>{KIND[job.kind]} · {bytes(job.input_bytes)}</p></div><Badge status={job.status}/></div><div className="detail-facts"><div><small>提交時間</small><strong>{date(job.created_at)}</strong></div><div><small>完整耗時</small><strong>{job.completed_at?duration(job.completed_at-job.created_at):'尚未完成'}</strong></div><div><small>執行次數</small><strong>{job.attempt_count} / 3</strong></div></div>{job.error&&<p className="error-box">{job.error}</p>}{job.waiting_reason&&<p className="inline-note"><Clock3 size={17}/>{job.waiting_reason}</p>}
 {job.status==='completed'&&<section className="result-preview"><div className="panel-heading"><h3>成果預覽</h3><span className="verified"><CheckCircle2 size={16}/>已回傳 GPU 執行紀錄</span></div>{job.kind==='asr'?<><audio controls preload="metadata" src={'/api/jobs/'+job.id+'/input'}/><div className="transcript">{textError||text||'正在載入逐字稿…'}</div></>:output&&<><div className="image-comparison"><img src={'/api/artifacts/'+output.id} alt="AI 放大後的圖片"/><div className="before-layer" style={{clipPath:`inset(0 ${100-split}% 0 0)`}}><img src={'/api/jobs/'+job.id+'/input'} alt="原始圖片"/></div><span className="image-label before">原圖</span><span className="image-label after">AI 2×</span><div className="comparison-line" style={{left:split+'%'}}/></div><label className="comparison-control">前後比較<input type="range" min="0" max="100" value={split} onChange={e=>setSplit(Number(e.target.value))} aria-label="調整圖片前後比較"/></label></>}<div className="download-links">{job.artifacts.map(a=><a key={a.id} className="button secondary" href={'/api/artifacts/'+a.id+'?download=true'}><Download size={16}/>{a.name}</a>)}</div></section>}
 <section className="attempt-section"><h3>接力紀錄</h3>{job.attempts.length?<ol className="timeline">{job.attempts.map((a,i)=><li key={a.id}><span className={'timeline-dot '+(a.outcome==='completed'?'success':'')}>{i+1}</span><div><strong>{a.node_name}</strong><small>{a.gpu_name} · {date(a.started_at)}</small><p>{a.outcome==='completed'?'處理完成':a.error||job.stage}{a.ended_at&&` · ${duration(a.ended_at-a.started_at)}`}</p></div></li>)}</ol>:<p className="muted">尚未分配至設備。工作會保留在佇列中。</p>}</section></Modal>
}

