import { useState } from 'react';
import { Cpu,Plus,Clock3,Settings,Copy,ShieldCheck,Power,CheckCircle2,Info } from 'lucide-react';
import { api } from './api';
import { type State,type Action,type Node,nodeStatus,duration,KIND } from './types';
import { Modal,Empty } from './ui';
export function Nodes({state,action}:{state:State;action:Action}){
 const [pair,setPair]=useState<{code:string;expires_in:number}|null>(null);const [edit,setEdit]=useState<Node|null>(null);const [stop,setStop]=useState<Node|null>(null);const [onlyMine,setOnlyMine]=useState(false);
 const nodes=state.nodes.filter(n=>!n.revoked&&(!onlyMine||n.owner_id===state.user.id));
 return <><div className="page-heading"><div><span className="eyebrow">校園共享算力池</span><h1>每台設備，都是一份助力。</h1><p>開啟分享前先啟動本機接力程式。你可以隨時收回自己的電腦。</p></div><button className="primary" onClick={()=>action(async()=>setPair(await api<{code:string;expires_in:number}>('/pairing-codes','POST')))}><Plus size={18}/>加入我的設備</button></div><div className="toolbar"><div className="segmented"><button className={!onlyMine?'chosen':''} onClick={()=>setOnlyMine(false)}>全部設備</button><button className={onlyMine?'chosen':''} onClick={()=>setOnlyMine(true)}>我的設備</button></div><span className="result-count">{nodes.length} 台設備</span></div>
 {!nodes.length?<section className="panel"><Empty title="準備迎接第一台共享 GPU" description="取得一次性配對碼，接著在你的 GPU 電腦執行接力程式。"/></section>:<div className="nodes-grid">{nodes.map(n=>{const mine=n.owner_id===state.user.id||state.user.role==='admin';const t=n.telemetry;return <section className={'panel node-card '+(n.current_job?'working':'')} key={n.id}><div className="node-card-heading"><div className="node-symbol"><Cpu size={26}/></div><div><h2>{n.name}</h2><p>{n.gpu_name}</p></div><span className={'node-status '+(n.online&&n.sharing?'on':'')}>{nodeStatus(n)}</span></div><div className="node-specs"><span>{(n.memory_mb/1024).toFixed(1)} GB VRAM</span>{Object.keys(n.capabilities).map(k=><span key={k}>{KIND[k as keyof typeof KIND]}</span>)}</div><div className="gpu-meter"><div><span>GPU 使用率</span><strong>{n.online&&t.gpu_utilization!=null?t.gpu_utilization+'%':'未提供'}</strong></div><div className="meter-track"><span style={{width:(n.online?t.gpu_utilization||0:0)+'%'}}/></div></div><div className="node-telemetry"><div><small>顯示記憶體</small><strong>{n.online&&t.memory_used_mb!=null?(t.memory_used_mb/1024).toFixed(1)+' GB':'未提供'}</strong></div><div><small>溫度</small><strong>{n.online&&t.temperature_c!=null?t.temperature_c+'°C':'未提供'}</strong></div><div><small>電源</small><strong>{!n.online||t.on_ac==null?'未提供':t.on_ac?'已插電':'電池供電'}</strong></div></div><div className="node-current"><span className={n.current_job?'pulse-dot':''}/>{n.current_job?`${KIND[n.current_job.kind]} · ${n.current_job.stage}`:'目前沒有執行中的工作'}</div><div className="node-contribution"><span><CheckCircle2 size={15}/>{n.completed_count} 件已完成</span><span><Clock3 size={15}/>{duration(n.compute_seconds)}</span></div><div className="node-controls"><span>{n.schedule_start?`${n.schedule_start}–${n.schedule_end}`:'手動共享 · 隨時收回'}</span>{mine?<><button className="icon-button" aria-label={`設定 ${n.name}`} onClick={()=>setEdit(n)}><Settings size={18}/></button><button className={'share-toggle '+(n.sharing?'enabled':'')} role="switch" aria-checked={!!n.sharing} aria-label={`${n.name} 分享開關`} onClick={()=>n.sharing?setStop(n):action(async()=>{await api('/nodes/'+n.id,'PATCH',{sharing:true})},'已允許設備接單')}><span/>{n.sharing?'ON':'OFF'}</button></>:<span className="muted">由機主管理</span>}</div>{mine&&!!n.sharing&&!n.local_enabled&&<p className="inline-note"><Info size={16}/>本機接力程式目前停止接單，請在該電腦啟用。</p>}</section>})}</div>}
 <section className="provider-notice"><ShieldCheck size={23}/><div><strong>分享的前提，是你保有控制權。</strong><p>每張 GPU 同時執行一個平台工作。停止共享會終止當前工作，尚未完成的檔案重新排隊；支援的工作由該設備實際通過的模型測試決定。</p></div></section>
 {pair&&<Modal title="加入我的 GPU 設備" onClose={()=>setPair(null)}><ol className="setup-list"><li>在 GPU 電腦準備好 Docker，啟動接力程式。</li><li>輸入中央服務網址與下方配對碼。</li><li>完成環境檢查，再回到這裡開啟分享。</li></ol><div className="pair-code"><small>一次性配對碼 · 10 分鐘內有效</small><code>{pair.code}</code><button className="secondary" onClick={()=>navigator.clipboard.writeText(pair.code)}><Copy size={16}/>複製配對碼</button></div><p className="muted">配對碼僅使用一次。請只在你管理的設備輸入，勿交給陌生人。</p><div className="modal-actions"><button className="primary" onClick={()=>setPair(null)}>我知道了</button></div></Modal>}
 {stop&&<Modal title="收回這台電腦？" onClose={()=>setStop(null)}><p>「{stop.name}」將停止接單及當前工作。未完成的檔案會重新排隊，由可用設備接手。</p><div className="modal-actions"><button className="secondary" onClick={()=>setStop(null)}>繼續共享</button><button className="danger" onClick={()=>action(async()=>{await api('/nodes/'+stop.id,'PATCH',{sharing:false});setStop(null)},'已送出收回指令')}><Power size={17}/>停止共享</button></div></Modal>}
 {edit&&<Modal title="設備設定" onClose={()=>setEdit(null)}><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);action(async()=>{await api('/nodes/'+edit.id,'PATCH',{name:form.get('name'),schedule_start:form.get('start')||null,schedule_end:form.get('end')||null,utc_offset_minutes:Number(form.get('offset'))});setEdit(null)},'設備設定已儲存')}}><label>設備名稱<input name="name" defaultValue={edit.name} required maxLength={60}/></label><div className="form-two"><label>分享開始<input name="start" type="time" defaultValue={edit.schedule_start||''}/></label><label>分享結束<input name="end" type="time" defaultValue={edit.schedule_end||''}/></label></div><input type="hidden" name="offset" value={edit.utc_offset_minutes}/><p className="muted">時區 UTC{edit.utc_offset_minutes>=0?'+':''}{edit.utc_offset_minutes/60}。開始與結束皆留白表示不限時段；跨午夜時段也支援。</p><section className="environment-checks" aria-label="設備環境檢查"><h3>設備環境檢查</h3><dl><dt>顯示卡</dt><dd>{edit.gpu_name}</dd><dt>顯示記憶體</dt><dd>{(edit.memory_mb/1024).toFixed(1)} GB</dd><dt>顯示卡驅動</dt><dd>{String(edit.environment?.driver||'未提供')}</dd><dt>作業系統</dt><dd>{String(edit.environment?.os||'未提供')}</dd><dt>接力程式</dt><dd>{edit.online?'已連線':'離線，請啟動本機程式'}</dd></dl>{(['asr','upscale'] as const).map(kind=><div className="environment-service" key={kind}><strong>{KIND[kind]}</strong><span>{edit.capabilities[kind]?.cuda_verified?'已通過本機 GPU 與模型測試':'尚未通過本機測試'}</span></div>)}<p className="muted">以最近一次設備回報為準。更新驅動或模型後，請重新執行環境檢查。</p><details><summary>技術診斷資料</summary><pre className="environment-json">{JSON.stringify(edit.environment,null,2)}</pre></details></section><div className="modal-actions"><button className="secondary" type="button" onClick={()=>setEdit(null)}>取消</button><button className="primary">儲存設定</button></div></form></Modal>}</>
}


