import { useState,useRef } from 'react';
import { AudioLines,ScanLine,UploadCloud,ArrowUpRight,FileAudio,FileImage,X,ArrowRight,Clock3,Check,Info } from 'lucide-react';
import { upload } from './api';
import { type State,type Action,type Kind,KIND,bytes,active,pending,date,nodeStatus } from './types';
import { Stat,Badge,Empty } from './ui';
export function Workbench({state,action,onJobs}:{state:State;action:Action;onJobs:()=>void}){
 const [kind,setKind]=useState<Kind>('asr');const [files,setFiles]=useState<File[]>([]);const [name,setName]=useState('');const [demo,setDemo]=useState(false);const [busy,setBusy]=useState(false);const [progress,setProgress]=useState(0);const [drag,setDrag]=useState(false);const [validation,setValidation]=useState('');const input=useRef<HTMLInputElement>(null);
 const jobs=state.jobs.filter(j=>j.user_id===state.user.id);const ready=state.nodes.filter(n=>n.online&&n.sharing&&n.local_enabled&&n.within_schedule&&!n.revoked&&Object.keys(n.capabilities).length);
 function addFiles(newFiles:File[]){const next=[...files,...newFiles];if(next.length>state.limits.max_batch_files){setValidation(`每批最多 ${state.limits.max_batch_files} 個檔案`);return}if(next.some(f=>f.size>state.limits.max_file_mb*1024*1024)){setValidation(`每個檔案最多 ${state.limits.max_file_mb} MB`);return}setValidation('');setFiles(next)}
 const Icon=kind==='asr'?FileAudio:FileImage;
 return <><section className="page-heading"><div><span className="eyebrow">你的算力工作空間</span><h1>準備好，交給算力接力。</h1><p>選擇任務、上傳檔案，完成後在這裡取得成果。</p></div><button className="secondary" onClick={onJobs}>查看所有工作 <ArrowUpRight size={17}/></button></section>
 <div className="stats-grid"><Stat label="可共享 GPU" value={ready.length} detail={`已登錄 ${state.nodes.filter(n=>!n.revoked).length} 台設備`} accent/><Stat label="我的執行中工作" value={jobs.filter(j=>active(j.status)).length} detail={`同時執行上限 ${state.user.max_running} 件`}/><Stat label="等待接力" value={jobs.filter(j=>pending(j.status)).length} detail="設備可用時自動分配"/><Stat label="已完成成果" value={jobs.filter(j=>j.status==='completed').length} detail="可預覽與下載結果"/></div>
 <div className="workbench-grid"><section className="panel new-task"><div className="panel-heading"><h2>建立新任務</h2><span className="step-label">01 — 選擇處理方式</span></div><div className="task-options"><button className={'task-option '+(kind==='asr'?'chosen':'')} onClick={()=>{setKind('asr');setFiles([]);setValidation('')}} aria-pressed={kind==='asr'}><span className="task-option-icon"><AudioLines size={25}/></span><span><strong>語音轉文字</strong><small>音訊 → 逐字稿與字幕</small></span>{kind==='asr'&&<Check size={16}/>}</button><button className={'task-option '+(kind==='upscale'?'chosen':'')} onClick={()=>{setKind('upscale');setFiles([]);setValidation('')}} aria-pressed={kind==='upscale'}><span className="task-option-icon purple"><ScanLine size={25}/></span><span><strong>圖片 AI 放大</strong><small>圖片 → 2 倍細節放大</small></span>{kind==='upscale'&&<Check size={16}/>}</button></div>
 <form onSubmit={async e=>{e.preventDefault();if(!files.length){setValidation('請先選擇檔案');return}setBusy(true);setProgress(0);await action(async()=>{const form=new FormData();form.set('kind',kind);form.set('name',name||`${KIND[kind]} · ${new Date().toLocaleDateString('zh-TW')}`);form.set('is_demo',String(demo));files.forEach(f=>form.append('files',f));await upload(form,setProgress);setFiles([]);setName('');onJobs()},'工作已加入佇列');setBusy(false)}}>
 <div className="form-section-label"><span className="step-label">02 — 加入檔案</span><span>{files.length} / {state.limits.max_batch_files}</span></div><div className={'dropzone '+(drag?'drag':'')} role="button" tabIndex={0} aria-label="選擇或拖曳上傳檔案" onClick={()=>input.current?.click()} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.current?.click()}}} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);addFiles(Array.from(e.dataTransfer.files))}}><div className="upload-icon"><UploadCloud size={25}/></div><strong>拖曳檔案到這裡，或<span>選擇檔案</span></strong><p>{kind==='asr'?'WAV、MP3、M4A、FLAC、OGG、MP4、WebM':'PNG、JPG、WebP · 寬高各不超過 2048 px'}</p><small>每個檔案最多 {state.limits.max_file_mb} MB · 單批總量最多 150 MB</small></div><input ref={input} className="sr-only" type="file" multiple accept={kind==='asr'?'.wav,.mp3,.m4a,.flac,.ogg,.mp4,.webm':'.png,.jpg,.jpeg,.webp'} onChange={e=>{addFiles(Array.from(e.target.files||[]));e.target.value=''}}/>
 {validation&&<p role="alert" className="error-box">{validation}</p>}{files.length>0&&<div className="file-list">{files.map((f,i)=><div className="file-row" key={i}><Icon size={20}/><span>{f.name}<small>{bytes(f.size)}</small></span><button type="button" className="icon-button" aria-label={`移除 ${f.name}`} onClick={()=>setFiles(files.filter((_,x)=>x!==i))}><X size={17}/></button></div>)}</div>}
 <label className="compact-label">批次名稱 <span>選填</span><input value={name} maxLength={80} onChange={e=>setName(e.target.value)} placeholder={kind==='asr'?'例如：社團訪談逐字稿':'例如：活動照片放大'}/></label><label className="checkbox-label"><input type="checkbox" checked={demo} onChange={e=>setDemo(e.target.checked)}/>這是示範資料，可由管理者重置</label>
 {!ready.some(n=>n.capabilities[kind])&&<div className="inline-note"><Clock3 size={17}/>目前沒有可共享且支援此任務的設備，提交後會先排隊。</div>}<div className="submit-row"><span><Info size={15}/>僅上傳有權使用、可交由共享設備處理的資料。</span><button className="primary" disabled={busy} type="submit">{busy?`上傳中 ${Math.round(progress*100)}%`:'提交任務'}<ArrowRight size={18}/></button></div>
 </form></section><aside className="workbench-aside"><section className="panel pool-panel"><div className="panel-heading"><h2>算力池</h2><span className="pill">即時</span></div>{state.nodes.filter(n=>!n.revoked).length?state.nodes.filter(n=>!n.revoked).slice(0,5).map(n=><div className="pool-node" key={n.id}><span className={'node-light '+(n.online&&n.sharing?'on':'')}/><div><strong>{n.name}</strong><small>{n.gpu_name}</small></div><span className="mono">{nodeStatus(n)}</span></div>):<div className="small-empty"><div className="gpu-placeholder"><ScanLine size={28}/></div><strong>等待第一台設備加入</strong><p>從「共享設備」取得配對碼，<br/>在提供 GPU 的電腦啟動接力程式。</p></div>}<div className="pool-foot">設備可隨時加入、退出；工作會保留在佇列。</div></section><section className="relay-explainer"><span className="eyebrow">每個工作，都有下一棒</span><h3>臨時需要電腦？<br/>把工作交給下一台。</h3><p>機主停止共享後，尚未完成的檔案重新排隊。已完成的成果會保留。</p><div className="relay-steps"><span>提交</span><i/><span>運算</span><i/><span>完成</span></div></section></aside></div>
 <section className="panel recent-panel"><div className="panel-heading"><h2>最近工作</h2><button className="text-button" onClick={onJobs}>全部工作 <ArrowRight size={16}/></button></div>{jobs.length?<div className="table-wrap"><table><thead><tr><th>檔案 / 任務</th><th>類型</th><th>狀態</th><th>提交時間</th><th>執行節點</th></tr></thead><tbody>{jobs.slice(0,5).map(j=><tr key={j.id}><td><strong>{j.filename}</strong><small>{j.batch_name}</small></td><td>{KIND[j.kind]}</td><td><Badge status={j.status}/></td><td>{date(j.created_at)}</td><td>{j.attempts.at(-1)?.node_name||'等待分配'}</td></tr>)}</tbody></table></div>:<Empty title="你的第一個成果，從這裡開始" description="上傳音訊或圖片，任務與結果會出現在這裡。"/>}</section></>
}

