# Generated by Django 5.2.17 on 2026-09-16 17:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', '待開始'), ('active', '使用中'), ('done', '已結束'), ('cancelled', '已取消'), ('failed', '開通失敗')], default='pending', max_length=10)),
                ('access_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cpu_model', models.CharField(max_length=100)),
                ('gpu_model', models.CharField(blank=True, max_length=100, null=True)),
                ('ram_gb', models.IntegerField()),
                ('gpu_vram_gb', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('idle', '閒置'), ('busy', '擁有者使用中'), ('rented', '租用中'), ('offline', '離線')], default='offline', max_length=10)),
                ('owner_dept', models.CharField(max_length=100)),
                ('agent_token_hash', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('student', '學生'), ('staff', '教職員')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UsageReport',
            fields=[
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='report', serialize=False, to='core.booking')),
                ('duration_hours', models.FloatField()),
                ('cpu_avg', models.FloatField()),
                ('gpu_avg', models.FloatField(blank=True, null=True)),
                ('summary_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.machine'),
        ),
        migrations.CreateModel(
            name='AvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='core.machine')),
            ],
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('start', '開通容器'), ('stop', '回收容器')], max_length=10)),
                ('status', models.CharField(choices=[('pending', '待領取'), ('claimed', '執行中'), ('succeeded', '成功'), ('failed', '失敗')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.booking')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.machine')),
            ],
        ),
        migrations.CreateModel(
            name='AgentHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField()),
                ('ram_percent', models.FloatField()),
                ('gpu_percent', models.FloatField(blank=True, null=True)),
                ('gpu_vram_used_gb', models.FloatField(blank=True, null=True)),
                ('owner_active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='core.machine')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['student', 'staff'])), name='user_role_valid'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['machine', 'start_time'], name='core_bookin_machine_db8da3_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='booking_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='availabilitywindow',
            index=models.Index(fields=['machine', 'start_time'], name='core_availa_machine_4a231f_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilitywindow',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='window_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='agenttask',
            index=models.Index(fields=['machine', 'status', 'created_at'], name='core_agentt_machine_62d757_idx'),
        ),
        migrations.AddConstraint(
            model_name='agenttask',
            constraint=models.UniqueConstraint(fields=('booking', 'action'), name='one_task_per_booking_action'),
        ),
        migrations.AddIndex(
            model_name='agentheartbeat',
            index=models.Index(fields=['machine', '-timestamp'], name='core_agenth_machine_c21fe0_idx'),
        ),
    ]
