# Generated by Django 5.2.17 on 2026-09-18 10:36

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('student', '學生'), ('staff', '教職員')], max_length=10)),
                ('max_running', models.PositiveSmallIntegerField(default=2)),
                ('daily_limit', models.PositiveIntegerField(default=100)),
                ('last_dispatch', models.BigIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('asr', 'asr'), ('upscale', 'upscale')], max_length=10)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('asr', 'asr'), ('upscale', 'upscale')], max_length=10)),
                ('profile', models.CharField(max_length=40)),
                ('filename', models.CharField(max_length=255)),
                ('input_file', models.FileField(max_length=255, upload_to=core.models.job_input_path)),
                ('input_bytes', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('queued', '排隊中'), ('loading', '準備中'), ('running', '執行中'), ('retrying', '重新排隊'), ('completed', '已完成'), ('failed', '失敗'), ('cancelled', '已取消')], default='queued', max_length=10)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('stage', models.CharField(default='等待可用設備', max_length=20)),
                ('progress', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=255, upload_to=core.models.artifact_path)),
                ('media_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('gpu_uuid', models.CharField(max_length=100, unique=True)),
                ('gpu_name', models.CharField(max_length=120)),
                ('memory_mb', models.PositiveIntegerField()),
                ('capabilities', models.JSONField(default=dict)),
                ('environment', models.JSONField(default=dict)),
                ('telemetry', models.JSONField(default=dict)),
                ('sharing', models.BooleanField(default=False)),
                ('local_enabled', models.BooleanField(default=False)),
                ('revoked', models.BooleanField(default=False)),
                ('schedule_start', models.CharField(blank=True, max_length=5, null=True)),
                ('schedule_end', models.CharField(blank=True, max_length=5, null=True)),
                ('utc_offset_minutes', models.SmallIntegerField(default=480)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.job')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.node')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('lease_until', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=20)),
                ('error', models.TextField(blank=True)),
                ('gpu_verified', models.BooleanField(default=False)),
                ('metrics', models.JSONField(default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.job')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='core.node')),
            ],
        ),
        migrations.CreateModel(
            name='PairingCode',
            fields=[
                ('code_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['student', 'staff'])), name='user_role_valid'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_at'], name='core_job_status_38dcf0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', '-created_at'], name='core_job_user_id_3056b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', '-id'], name='core_event_user_id_9a34da_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['ended_at', 'lease_until'], name='core_attemp_ended_a_b2f783_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('node',), name='one_active_attempt_per_node'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('job',), name='one_active_attempt_per_job'),
        ),
    ]
