# Generated by Django 5.2.17 on 2026-09-23 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='allow_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='kind',
            field=models.CharField(choices=[('asr', 'asr'), ('upscale', 'upscale'), ('render', 'render'), ('animate', 'animate'), ('dataset', 'dataset'), ('train', 'train')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.CharField(choices=[('asr', 'asr'), ('upscale', 'upscale'), ('render', 'render'), ('animate', 'animate'), ('dataset', 'dataset'), ('train', 'train')], max_length=10),
        ),
        migrations.CreateModel(
            name='NodeDailyUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('busy_seconds', models.FloatField(default=0)),
                ('rented_seconds', models.FloatField(default=0)),
                ('idle_seconds', models.FloatField(default=0)),
                ('offline_seconds', models.FloatField(default=0)),
                ('gpu_seconds', models.FloatField(default=0)),
                ('jobs_completed', models.PositiveIntegerField(default=0)),
                ('samples', models.PositiveIntegerField(default=0)),
                ('avg_utilization', models.FloatField(blank=True, null=True)),
                ('peak_utilization', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='core.node')),
            ],
            options={
                'indexes': [models.Index(fields=['-day'], name='core_nodeda_day_e7cc2d_idx')],
                'constraints': [models.UniqueConstraint(fields=('node', 'day'), name='one_usage_row_per_node_day')],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=120)),
                ('minutes', models.PositiveSmallIntegerField()),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('queued', '排隊中'), ('starting', '啟動中'), ('active', '使用中'), ('ending', '結束中'), ('ended', '已結束'), ('expired', '已到期'), ('failed', '啟動失敗'), ('cancelled', '已取消')], default='queued', max_length=10)),
                ('connect_url', models.CharField(blank=True, max_length=300)),
                ('connect_token', models.CharField(blank=True, max_length=120)),
                ('connection', models.JSONField(default=dict)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=200)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='core.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_rental_status_3b8077_idx'), models.Index(fields=['user', '-created_at'], name='core_rental_user_id_a1bf93_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['starting', 'active', 'ending'])), fields=('node',), name='one_open_rental_per_node')],
            },
        ),
        migrations.CreateModel(
            name='UsageSample',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('busy', '執行工作'), ('rented', '租借中'), ('idle', '閒置可用'), ('paused', '未開放'), ('offline', '離線')], max_length=10)),
                ('gpu_utilization', models.FloatField(blank=True, null=True)),
                ('memory_used_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('power_w', models.FloatField(blank=True, null=True)),
                ('interval_seconds', models.FloatField(default=0)),
                ('busy_seconds', models.FloatField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_samples', to='core.node')),
            ],
            options={
                'indexes': [models.Index(fields=['node', '-captured_at'], name='core_usages_node_id_d10a95_idx'), models.Index(fields=['-captured_at'], name='core_usages_capture_945e69_idx')],
            },
        ),
    ]
