# Generated by Django 5.2.17 on 2026-09-23 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_id_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[一-鿿㐀-䶿A-Za-z][一-鿿㐀-䶿A-Za-z ·．・'\\-]*$", '姓名只能使用中文或英文字母,不可含數字或符號')]),
        ),
    ]
