# Generated by Django 5.2.17 on 2026-09-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='prepared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='progress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='stage',
            field=models.CharField(default='等待可用設備', max_length=20),
        ),
    ]
